site_name: MyDocs
nav:
  - Home: index.md
  - AWS-cli: awsCLI.md
  - Mkdocs: mkdocs.md
  - Learning: learning.md
  - Macbook: mac_install.md
  - ldapsearch: ldap_search.md
  - Videos: videos.md
  - Links: links.md
  - About: about.md
theme: readthedocs